# msa-user Rollout
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: eks-canary-deployment
  name: msa-user
  labels:
    app: msa-user
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: msa-user
  template:
    metadata:
      labels:
        app: msa-user
    spec:
      containers:
      - name: msa-user
        image: chadchae1373/msa_user:$(IMAGE_VERSION) # ConfigMap에서 버전 가져오기
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "msa-db-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "12341234"
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: { duration: 2m }
      - setWeight: 60
      - pause: { duration: 3m }
      - setWeight: 100

---

# msa-user Service
apiVersion: v1
kind: Service
metadata:
  namespace: eks-canary-deployment
  name: msa-user
  labels:
    app: msa-user
spec:
  type: LoadBalancer
  selector:
    app: msa-user
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080