
# msa-review Rollout
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: eks-canary-deployment
  name: msa-review
  labels:
    app: msa-review
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: msa-review
  template:
    metadata:
      labels:
        app: msa-review
    spec:
      containers:
      - name: msa-review
        image: chadchae1373/msa_review:$(IMAGE_VERSION) # ConfigMap에서 버전 가져오기
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "msa-db-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "12341234"
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: { duration: 1m }
      - setWeight: 50
      - pause: { duration: 2m }
      - setWeight: 100

---

# msa-review Service
apiVersion: v1
kind: Service
metadata:
  namespace: eks-canary-deployment
  name: msa-review
  labels:
    app: msa-review
spec:
  type: LoadBalancer
  selector:
    app: msa-review
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
